package yuma140902.misc_things;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import yuma140902.misc_things.config.MTConfigCore;
import yuma140902.misc_things.proxy.MTCommonProxy;
import yuma140902.yumalib.api.context.InitModContext;
import yuma140902.yumalib.api.registry.Contexts;
import yuma140902.yumalib.api.util.NameProvider;

@Mod(modid = MTConstants.MOD_ID, name = MTConstants.MOD_NAME, version = MTConstants.MOD_VERSION, useMetadata = true, guiFactory = MTConstants.CONFIG_GUI_FACTORY,
dependencies = "after:uptodate;required-after:yumalib"
)
public class ModMiscThings {
	
	public static final Logger LOGGER = LogManager.getLogger(MTConstants.MOD_NAME);
	
	@Mod.Metadata(MTConstants.MOD_ID)
	public static ModMetadata modMetadata;
	
	@Mod.Instance(MTConstants.MOD_ID)
	public static ModMiscThings INSTANCE;
	
	@SidedProxy(modId = MTConstants.MOD_ID, clientSide = MTConstants.PROXY_CLIENT, serverSide = MTConstants.PROXY_COMMON)
	public static MTCommonProxy proxy;
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = MTConstants.MOD_ID;
		modMetadata.name = MTConstants.MOD_NAME;
		modMetadata.version = MTConstants.MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "Miscellaneous Things";
		//modMetadata.url = "https://www.curseforge.com/minecraft/mc-mods/yumalib";
		modMetadata.autogenerated = false;
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
		MTConfigCore.loadConfig(event);
		
		Contexts.setContext(new InitModContext(MTConstants.MOD_NAME, new NameProvider(MTConstants.MOD_ID, MTConstants.MOD_ID)));
		
		proxy.registerEventHandlers();
		
		Contexts.removeContext();
	}
}

