package yuma140902.yumalib;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import yuma140902.yumalib.api.update.IUpdateChecker;
import yuma140902.yumalib.api.update.UpdateCheckerRegistry;
import yuma140902.yumalib.config.YLConfigCore;
import yuma140902.yumalib.proxy.YLCommonProxy;

@Mod(modid = YTConstants.MOD_ID, name = YTConstants.MOD_NAME, version = YTConstants.MOD_VERSION, useMetadata = true, guiFactory = YTConstants.CONFIG_GUI_FACTORY)
public class ModYumaLib {
	
	public static final Logger LOGGER = LogManager.getLogger(YTConstants.MOD_NAME);
	
	@Mod.Metadata(YTConstants.MOD_ID)
	public static ModMetadata modMetadata;
	
	@Mod.Instance(YTConstants.MOD_ID)
	public static ModYumaLib INSTANCE;
	
	@SidedProxy(modId = YTConstants.MOD_ID, clientSide = YTConstants.PROXY_CLIENT, serverSide = YTConstants.PROXY_COMMON)
	public static YLCommonProxy proxy;
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = YTConstants.MOD_ID;
		modMetadata.name = YTConstants.MOD_NAME;
		modMetadata.version = YTConstants.MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "Library for UpToDateMod";
		//modMetadata.url = "https://www.curseforge.com/minecraft/mc-mods/yumalib";
		modMetadata.autogenerated = false;
		modMetadata.logoFile = "assets/yumalib/textures/logo.png";
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
		proxy.checkIfIsYuma140902();
		YLConfigCore.loadConfig(event);
		proxy.registerEventHandlers();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		for(IUpdateChecker updateChecker : UpdateCheckerRegistry.INSTANCE.list()) {
			try {
				updateChecker.checkForUpdates();
			}
			catch (Exception e) {
				e.printStackTrace();
			}
		}
		
	}
}
