package yuma140902.mcmodlib;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = YumaLibConstants.MOD_ID, name = YumaLibConstants.MOD_NAME, version = YumaLibConstants.MOD_VERSION, useMetadata = true)
public class ModYumaLib {
	
	public static final Logger LOGGER = LogManager.getLogger(YumaLibConstants.MOD_NAME);
	
	@Mod.Metadata(YumaLibConstants.MOD_ID)
	public static ModMetadata modMetadata;
	
	@Mod.Instance(YumaLibConstants.MOD_ID)
	public static ModYumaLib INSTANCE;
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = YumaLibConstants.MOD_ID;
		modMetadata.name = YumaLibConstants.MOD_NAME;
		modMetadata.version = YumaLibConstants.MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "Library for my mods";
		modMetadata.url = "https://www.curseforge.com/minecraft/mc-mods/yumalib";
		modMetadata.autogenerated = false;
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
	}
}
